// Cart Action Types
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

// Checkout Action Types
export const SET_SUBTOTAL = "SET_SUBTOTAL";
export const SET_DISCOUNTED_SUBTOTAL = "SET_DISCOUNTED_SUBTOTAL";
export const SET_TOTAL = "SET_TOTAL";
export const SET_DISCOUNTED_TOTAL = "SET_DISCOUNTED_TOTAL";
export const SET_SHIPPING_FEES = "SET_SHIPPING_FEES";