// Cart Action Types
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const SET_BUY_NOW_PRODUCT = "SET_BUY_NOW_PRODUCT";
export const RESET_CART = "RESET_CART";

// Checkout Action Types
export const SET_SUBTOTAL = "SET_SUBTOTAL";
export const SET_DISCOUNTED_SUBTOTAL = "SET_DISCOUNTED_SUBTOTAL";
export const SET_TOTAL = "SET_TOTAL";
export const SET_BUY_NOW_PRODUCT_PRICE = "SET_BUY_NOW_PRODUCT_PRICE";
export const SET_SHIPPING_FEES = "SET_SHIPPING_FEES";
export const SET_DISCOUNTED_SHIPPING_FEES = "SET_DISCOUNTED_SHIPPING_FEES";
export const SET_FREE_SHIPPING = "SET_FREE_SHIPPING";
export const SET_COUPON_CODE_AVAILABILITY = "SET_COUPON_CODE_AVAILABILITY";
export const SET_ENTERED_COUPON_CODE = "SET_ENTERED_COUPON_CODE";
export const SET_USED_COUPON_CODE = "SET_USED_COUPON_CODE";
export const SET_COUPON_ERROR_MESSAGE = "SET_COUPON_ERROR_MESSAGE";
export const SET_DISCOUNT_AMOUNT = "SET_DISCOUNT_AMOUNT";
export const SET_ORDER = {
    items: "SET_ORDER_ITEMS",
    subtotal: "SET_ORDER_SUBTOTAL",
    shipping: "SET_ORDER_SHIPPING",
    total: "SET_ORDER_TOTAL",
    coupon: "SET_ORDER_COUPON",
    discount: "SET_ORDER_DISCOUNT",
    date: "SET_ORDER_DATE",
}

//UserData Action Types
export const SET_EMAIL = "SET_EMAIL";
export const SET_DELIVERY_METHOD = "SET_DELIVERY_METHOD";
export const SET_COUNTRY = "SET_COUNTRY";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_APARTMENT = "SET_APARTMENT";
export const SET_CITY = "SET_CITY";
export const SET_ZIP_CODE = "SET_ZIP_CODE";
export const SET_SHIPPING_COST = "SET_SHIPPING_COST";
export const SET_IS_COUPON_USED = "SET_IS_COUPON_USED";
export const SET_IS_USER_DATA_VALID = "SET_IS_USER_DATA_VALID";